version: "3"
services:
  vdb:
    image: vdb_worker
    networks:
      - bridge-network
    expose:
      - "50051"
    deploy:
      mode: replicated
      replicas: 3
  server:
    image: vdb_server
    networks:
      - bridge-network
    ports:
      - "3000:3000"
      - "8000:8000"
    expose:
      - "8000"
      - "3000"
    deploy:
      mode: replicated
      replicas: 1

networks:
  bridge-network:
    driver: bridge
