# Use the official Python image with Python 3.11
FROM python:3.11

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install Python dependencies
RUN pip install -r requirements.txt

# Install Docker
RUN apt-get update && apt-get install -y docker.io

# Expose port 50051
EXPOSE 50051

# Run build_protos.sh
RUN ./build_protos.sh

# Execute Python application
ENTRYPOINT ["python", "vdb/app.py"]
